"""
config_schema.py
================
Shared data model and configuration schema for the spreadsheet-to-linear skill.

This module defines:
  - The expected spreadsheet column layout (SPREADSHEET_COLUMNS)
  - The SkillConfig dataclass (generated during Phase 0 preflight)
  - The TaskRecord dataclass (produced by parse_spreadsheet.py)
  - The MoSCoW label group name and valid values
  - Default estimate scale name

All other scripts import from this module to ensure a single source of truth.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
import json
import os

# ---------------------------------------------------------------------------
# Spreadsheet column layout (0-indexed)
# This is the authoritative definition of the expected .xlsx column order.
# ---------------------------------------------------------------------------

# The 18-column markdown task register layout (0-indexed)
SPREADSHEET_COLUMNS = {
    "row_type":           0,   # Row Type (PROJECT, SUBPROJECT, TASK)
    "task_id":            1,   # Task ID
    "subproject":         2,   # Sub-project
    "task_name":          3,   # Task name
    "owner_r":            4,   # Owner (R)
    "accountable_a":      5,   # Accountable (A)
    "consulted_c":        6,   # Consulted (C)
    "informed_i":         7,   # Informed (I)
    "dependencies":       8,   # Dependencies
    "estimated_hours":    9,   # Estimated hours
    "start_date":        10,   # Start date
    "end_date":          11,   # End date
    "percent_complete":  12,   # % Complete
    "status":            13,   # Status
    "sprint":            14,   # Sprint
    "context_why":       15,   # Context / Why
    "task_breakdown":    16,   # Task Breakdown
    "acceptance_criteria": 17, # Acceptance Criteria
}

# Human-readable column names for error messages
COLUMN_NAMES = {v: k for k, v in SPREADSHEET_COLUMNS.items()}

# Mandatory columns — rows missing these are skipped with a warning
REQUIRED_COLUMNS = {"task_id", "subproject", "task_name"}

# ---------------------------------------------------------------------------
# MoSCoW configuration
# ---------------------------------------------------------------------------

MOSCOW_LABEL_GROUP = "MoSCoW"
MOSCOW_VALUES = {"Must", "Should", "Could", "Won't"}
MOSCOW_ALIASES = {
    "must have": "Must", "must-have": "Must", "must": "Must",
    "should have": "Should", "should-have": "Should", "should": "Should",
    "could have": "Could", "could-have": "Could", "could": "Could",
    "won't have": "Won't", "wont have": "Won't", "won't": "Won't", "wont": "Won't",
}

def normalise_moscow(raw: str) -> Optional[str]:
    """Normalise a raw MoSCoW string to one of the four canonical values."""
    if not raw:
        return None
    cleaned = raw.strip().lower()
    if cleaned in MOSCOW_ALIASES:
        return MOSCOW_ALIASES[cleaned]
    # Try capitalised match
    cap = raw.strip().capitalize()
    if cap in MOSCOW_VALUES:
        return cap
    return None

# ---------------------------------------------------------------------------
# Status mapping: spreadsheet status → Linear workflow state name
# ---------------------------------------------------------------------------

STATUS_MAP = {
    "backlog":     "Backlog",
    "todo":        "Todo",
    "to do":       "Todo",
    "in progress": "In Progress",
    "inprogress":  "In Progress",
    "done":        "Done",
    "complete":    "Done",
    "completed":   "Done",
    "cancelled":   "Canceled",
    "canceled":    "Canceled",
}

def normalise_status(raw: str) -> str:
    """Map a raw status string to the Linear workflow state name."""
    if not raw:
        return "Backlog"
    return STATUS_MAP.get(raw.strip().lower(), "Backlog")

# ---------------------------------------------------------------------------
# Default estimate scale
# ---------------------------------------------------------------------------

DEFAULT_ESTIMATE_SCALE = "tshirt"

# ---------------------------------------------------------------------------
# SkillConfig — generated by preflight.py, consumed by parse_spreadsheet.py
# ---------------------------------------------------------------------------

@dataclass
class LinearMember:
    id: str
    name: str
    email: str
    display_name: str

@dataclass
class LinearLabel:
    id: str
    name: str
    group: str   # parent label group name

@dataclass
class LinearCycle:
    id: str
    name: str
    starts_at: str
    ends_at: str

@dataclass
class LinearTeam:
    id: str
    name: str
    key: str

@dataclass
class LinearStatus:
    id: str
    name: str
    type: str   # backlog | unstarted | started | completed | cancelled

@dataclass
class SkillConfig:
    """
    Produced by Phase 0 (preflight.py) and consumed by Phase 1 (parse_spreadsheet.py).
    Represents the resolved state of the Linear workspace at preflight time.
    """
    team: LinearTeam
    members: list[LinearMember] = field(default_factory=list)
    labels: list[LinearLabel] = field(default_factory=list)
    cycles: list[LinearCycle] = field(default_factory=list)
    statuses: list[LinearStatus] = field(default_factory=list)
    estimate_scale: str = DEFAULT_ESTIMATE_SCALE
    initiative_name: str = ""

    def save(self, path: str) -> None:
        """Serialise to JSON for use across phases."""
        with open(path, "w") as f:
            json.dump({
                "team": self.team.__dict__,
                "members": [m.__dict__ for m in self.members],
                "labels": [l.__dict__ for l in self.labels],
                "cycles": [c.__dict__ for c in self.cycles],
                "statuses": [s.__dict__ for s in self.statuses],
                "estimate_scale": self.estimate_scale,
                "initiative_name": self.initiative_name,
            }, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "SkillConfig":
        """Deserialise from JSON."""
        with open(path) as f:
            data = json.load(f)
        return cls(
            team=LinearTeam(**data["team"]),
            members=[LinearMember(**m) for m in data["members"]],
            labels=[LinearLabel(**l) for l in data["labels"]],
            cycles=[LinearCycle(**c) for c in data["cycles"]],
            statuses=[LinearStatus(**s) for s in data["statuses"]],
            estimate_scale=data.get("estimate_scale", DEFAULT_ESTIMATE_SCALE),
            initiative_name=data.get("initiative_name", ""),
        )

    def find_member(self, name_or_email: str) -> Optional[LinearMember]:
        """Case-insensitive lookup by name, display name, or email."""
        if not name_or_email:
            return None
        needle = name_or_email.strip().lower()
        for m in self.members:
            if (m.name.lower() == needle or
                m.email.lower() == needle or
                m.display_name.lower() == needle):
                return m
        return None

    def find_label(self, name: str, group: Optional[str] = None) -> Optional[LinearLabel]:
        """Lookup a label by name, optionally filtered by group."""
        needle = name.strip().lower()
        for l in self.labels:
            if l.name.lower() == needle:
                if group is None or l.group.lower() == group.lower():
                    return l
        return None

    def find_cycle(self, name: str) -> Optional[LinearCycle]:
        """Case-insensitive lookup by cycle name."""
        needle = name.strip().lower()
        for c in self.cycles:
            if c.name.lower() == needle:
                return c
        return None

    def find_status(self, name: str) -> Optional[LinearStatus]:
        """Case-insensitive lookup by status name."""
        needle = name.strip().lower()
        for s in self.statuses:
            if s.name.lower() == needle:
                return s
        return None

# ---------------------------------------------------------------------------
# TaskRecord — produced by parse_spreadsheet.py
# ---------------------------------------------------------------------------

@dataclass
class TaskRecord:
    """
    One row from the task register spreadsheet, fully parsed and resolved
    against the Linear workspace state.
    """
    # Raw spreadsheet fields
    task_id: str
    subproject: str
    task_name: str
    # moscow_raw removed from schema
    owner_raw: str
    accountable_raw: str
    consulted_raw: str
    informed_raw: str
    dependencies_raw: str
    estimated_hours_raw: str
    sprint_raw: str
    end_date_raw: str
    status_raw: str
    context_why: str
    task_breakdown: str
    acceptance_criteria: str

    # Resolved / derived fields (populated by parse_spreadsheet.py)
    # moscow removed from schema
    owner_id: Optional[str] = None
    owner_resolved: Optional[str] = None
    dependency_ids: list[str] = field(default_factory=list)   # Task IDs (e.g. ["T01"])
    cycle_id: Optional[str] = None
    cycle_resolved: Optional[str] = None
    status_name: str = "Backlog"
    status_id: Optional[str] = None
    estimate_points: Optional[int] = None
    estimate_label: Optional[str] = None

    # Validation flags
    warnings: list[str] = field(default_factory=list)

    @property
    def issue_title(self) -> str:
        return f"[{self.task_id}] {self.task_name}"

    @property
    def has_warnings(self) -> bool:
        return len(self.warnings) > 0
